# Generated by Django 5.2.4 on 2025-07-14 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='password',
        ),
    ]
