# Generated by Django 5.2.4 on 2025-07-06 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_name', models.CharField()),
                ('region', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now=True)),
                ('ship_date', models.DateField(auto_now=True)),
                ('order_priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('C', 'Critical')])),
                ('unit_sold', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.country')),
                ('item_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='product.item')),
            ],
        ),
    ]
