# Generated by Django 5.2.4 on 2025-07-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_order_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.BigIntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
