# Generated by Django 5.2.4 on 2025-07-04 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordering', '0002_alter_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_channel', models.CharField(choices=[('online', 'online'), ('offline', 'offline')])),
                ('unit_sold', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.country')),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ordering.order')),
            ],
        ),
    ]
